version: '3.8'

services:
  backend:
    build:
      dockerfile: Dockerfile.prod
    environment:
      - APP_ENV=production
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  celery-worker:
    build:
      dockerfile: Dockerfile.prod
    restart: always

  celery-beat:
    build:
      dockerfile: Dockerfile.prod
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  postgres:
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups

  redis:
    restart: always
